### ISSUE TITLE
commitgraphs 3.12.0 does not deploy under gitbucket 4.5

### ISSUE THREAD

**Issue by McFoggy** [yoshiyoshifujii/gitbucket-commitgraphs-plugin#11]
the commitgraphs plugin does not deploy in the community demo gitbucket webapplication that uses gitbucket 4.5, see http://gitbucket-community.herokuapp.com

the community project is hosted under: https://github.com/McFoggy/gitbucket-community.herokuapp.com

**Comment by yoshiyoshifujii** [comment]
update 4.5.
see https://github.com/yoshiyoshifujii/gitbucket-commitgraphs-plugin/releases/tag/4.5.0
thanks.

**Comment by McFoggy** [comment]
perfect I just updated the demo project 
![image](https://cloud.githubusercontent.com/assets/1119660/19571817/c0d5784a-96ff-11e6-9e0b-05da5faa5335.png)
