### ISSUE TITLE
compatibility with gitbucket 4.10

### ISSUE THREAD

**Issue by McFoggy** [yoshiyoshifujii/gitbucket-commitgraphs-plugin#14]
Please consider to adapt to gitbucket 4.10, see [release notes](https://gitbucket.github.io/gitbucket-news/gitbucket/2017/02/25/gitbucket-4.10.html)

**Comment by yoshiyoshifujii** [comment]
It corresponds.
https://github.com/yoshiyoshifujii/gitbucket-commitgraphs-plugin/releases/tag/4.10.0

**Comment by McFoggy** [comment]
sorry I didn't saw it while checking all referenced plugins.
